server:
  port: 8089
  servlet:
    context-path: /market-core
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
integration:
  cart-service:
    url: http://localhost:8888/cart
    connect-timeout: 2000
    read-timeout: 10000
    write-timeout: 2000