server:
  port: 8091
  servlet:
    context-path: /market-cart
utils:
  cart:
    prefix: marLiguros
integrations:
  core-service:
    url: http://localhost:8888/core
    timeouts:
      connection: 2000
      reading: 10000
      writing: 2000