server:
  port: 8091
  servlet:
    context-path: /market-cart
utils:
  cart:
    prefix: marLiguros
integration:
  core-service:
    url: http://localhost:8888/core
    connect-timeout: 2000
    read-timeout: 10000
    write-timeout: 2000