--SET search_path TO market;
--
--DROP TABLE IF EXISTS users CASCADE;
--CREATE TABLE IF NOT EXISTS users (
--    id BIGSERIAL PRIMARY KEY,
--    username    VARCHAR(255) NOT NULL UNIQUE,
--    password    VARCHAR(255) NOT NULL,
--    email       VARCHAR(255) NOT NULL UNIQUE,
--    created_at  TIMESTAMP DEFAULT current_timestamp,
--    updated_at  TIMESTAMP DEFAULT current_timestamp
--);
--
--DROP TABLE IF EXISTS roles CASCADE;
--CREATE TABLE IF NOT EXISTS roles (
--    id          BIGSERIAL PRIMARY KEY,
--    name        VARCHAR(255) NOT NULL UNIQUE,
--    created_at  TIMESTAMP DEFAULT current_timestamp,
--    updated_at  TIMESTAMP DEFAULT current_timestamp
--);
--
--DROP TABLE IF EXISTS users_roles CASCADE;
--CREATE TABLE IF NOT EXISTS users_roles (
--    user_id     BIGINT NOT NULL REFERENCES users (id),
--    role_id     BIGINT NOT NULL REFERENCES roles (id),
--    created_at  TIMESTAMP DEFAULT current_timestamp,
--    updated_at  TIMESTAMP DEFAULT current_timestamp,
--    PRIMARY KEY (user_id, role_id)
--);