server:
  port: 8089
  servlet:
    context-path: /market
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: admin
#  jpa:
#    show_sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL94Dialect
utils:
  cart:
    prefix: marLiguros