server:
  port: 8888

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: http://localhost:8089/
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
        #        - id: cart-service
        #          uri: http://localhost:8191/
        #          predicates:
        #            - Path=/cart/**
        #          filters:
        #            - StripPrefix=1
        #            - PrefixPath=/market-cart
        #            - JwtAuthFilter
        - id: auth-service
          uri: http://localhost:8090/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter

#logging:
#  level:
#    reactor:
#      netty: TRACE
#    org:
#      springframework:
#        cloud:
#          gateway: TRACE