spring:
  application:
    name: front-service
server:
  port: 8088
  servlet:
    context-path: /market
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      fetchRegister: false

